### ISSUE TITLE
还会继续更新吗

### ISSUE THREAD

**Issue by sinterwong** [zheng-yuwei/license-plate-generator#1]
双层黄车牌和大车新能源车牌之后还会继续更新吗

**Comment by zheng-yuwei** [comment]
应该不会了。当初做车牌生成是因为在做车牌识别，有两个目的：1. 补充数据；2. 平衡数据。现在其实数据量还算可以，然后平衡数据也有其他方法。加上这个生成的数据训练，其实提升不大了。

这个只能靠你自己参考`doc`下的`中华人民共和国机动车号牌.pdf`，根据规则修改代码了~
