### ISSUE TITLE
更多的车牌生成

### ISSUE THREAD

**Issue by yuto3o** [zheng-yuwei/license-plate-generator#3]
你好，后续有增加其他特种车牌的打算吗？

**Comment by zheng-yuwei** [comment]
没有了，不好意思

**Comment by yuto3o** [comment]
谢谢，你的方案给了我不小的启发。

**Comment by zheng-yuwei** [comment]
不用~不知道你那边是什么情况，实际上在我的实践中，这个车牌生成在前期还有些许作用，但是其实真实数据提升大得多。所以我后续也就没有用生成的车牌以及加其他车牌的生成了（也有可能车牌不够真，我看过用gan做车牌生成的，效果很逼真，基本人分辨不出来，但是gan网络的训练、多样性等可能是需要考虑的问题）。所以其实能够的话，建议还是使用真实车牌。然后关于车牌的检测和识别，可以看我yolo的项目和多标签分类（识别指标上比CRNN类的OCR算法要好，也有可能我没训练对，哈哈哈）的项目，这两个简单算法+数据，其实就可以达到很高甚至商用水平了（我看你也开源了yolo的repo，所以你可以看一下就ok，如果也在搞车牌识别，希望对你有所参考）

**Comment by yuto3o** [comment]
再次感谢
