### ISSUE TITLE
如何绘制模板？

### ISSUE THREAD

**Issue by handsomefengfeng** [zheng-yuwei/license-plate-generator#4]
文件夹里的新能源车牌不是很清楚，如何得到像其他类型车牌一样的高清bmp文件呢？ 

如果有的话是否可以分享一下~ 

感谢！！ ：）

**Comment by zheng-yuwei** [comment]
我是百度google下的。。。

**Comment by handsomefengfeng** [comment]
您还存储者其他更多的模板吗？~ 方便邮箱分享一下吗 ？  方便的话可以发给我吗 ~   感谢！ 我的邮箱：289888186@qq.com

**Comment by zheng-yuwei** [comment]
没有了。。。然后这个库也是好久前做的了，现在造数据应该用GAN了吧，哈哈哈哈
